### ISSUE TITLE
USA version support

### ISSUE THREAD

**Issue by rmsa5** [isage/alienhook#1]
Hi, will this work also with PCSE00445 (USA version of the game)? Is it only a matter of changing the tai config accordingly, or does the actual hook code require adaptation?
thanks in advance

**Comment by isage** [comment]
It should, so yeah, only a matter of config adaptation

**Comment by rmsa5** [comment]
I suggest editing your installation instruction the following way:
```
#Alien Shooter DLC unlocker
#Uncomment appropriate TitleID section
#*PCSB00561 #Europe
*PCSE00445 #USA
ur0:tai/alienhook.suprx
```

**Comment by isage** [comment]
Done.
